<#
   * RvTools Exporter
   Compatibility 5.1

   Script to automate the export of XLXS generated by RvTools organized in subfolders by Vcenter and date
   Support mutiple Vcenters.
   The account used to launch the script, must have permissions in Vcenters
   
#>


param
(
   $Servers = @("Server01.local","Server02.local"), #Vcenters 
   $BasePath = "\\10.1.1.1\RVTools_Export", # Path to save the reports
   $OldFileDays = 15 # Max days to keep the reports.
)

$Date = (Get-Date -f "yyyyMMdd")

foreach ($Server in $Servers)
{
   # Create Directory
   New-Item -Path "$BasePath\$Server\$Date" -ItemType Directory -ErrorAction SilentlyContinue | Out-Null 

   # Run Export
   . "C:\Program Files (x86)\RobWare\RVTools\RVTools.exe" -passthroughAuth -s $Server -c ExportAll2xlsx -d "$BasePath\$Server\$Date"

   # Cleanup old files
   $Items = Get-ChildItem -Directory "$BasePath\$server"
   foreach ($item in $items)
   {
      $itemDate = ("{0}/{1}/{2}" -f $item.name.Substring(6,2),$item.name.Substring(4,2),$item.name.Substring(0,4))
      if ((((Get-date).AddDays(-$OldFileDays))-(Get-Date($itemDate))).Days -gt 0)
      {
         $item | Remove-Item -Recurse
      }
   }
}
